-- MySQL Script generated by MySQL Workbench
-- Sat May 16 20:31:34 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`trenerzy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trenerzy` (
  `id_trenera` INT NOT NULL AUTO_INCREMENT,
  `imie_trenera` VARCHAR(45) NOT NULL,
  `nazwisko_trenera` VARCHAR(45) NOT NULL,
  `narodowosc_trenera` VARCHAR(80) NOT NULL,
  `data_urodzenia_trenera` DATE NOT NULL,
  PRIMARY KEY (`id_trenera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stadiony`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stadiony` (
  `id_stadionu` INT NOT NULL AUTO_INCREMENT,
  `nazwa_stadionu` VARCHAR(45) NOT NULL,
  `lokalizacja_stadionu` VARCHAR(45) NOT NULL,
  `pojemnosc_stadionu` INT NOT NULL,
  PRIMARY KEY (`id_stadionu`),
  UNIQUE INDEX `nazwa_stadionu_UNIQUE` (`nazwa_stadionu` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`druzyny`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`druzyny` (
  `id_druzyny` INT NOT NULL AUTO_INCREMENT,
  `nazwa_druzyny` VARCHAR(45) NOT NULL,
  `miasto_druzyny` VARCHAR(45) NOT NULL,
  `stadion` INT NOT NULL,
  `trener` INT NOT NULL,
  PRIMARY KEY (`id_druzyny`),
  INDEX `fk_2_idx` (`trener` ASC) VISIBLE,
  INDEX `fk_3_idx` (`stadion` ASC) VISIBLE,
  UNIQUE INDEX `trener_UNIQUE` (`trener` ASC) VISIBLE,
  UNIQUE INDEX `nazwa_druzyny_UNIQUE` (`nazwa_druzyny` ASC) VISIBLE,
  CONSTRAINT `fk_2`
    FOREIGN KEY (`trener`)
    REFERENCES `mydb`.`trenerzy` (`id_trenera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_3`
    FOREIGN KEY (`stadion`)
    REFERENCES `mydb`.`stadiony` (`id_stadionu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zawodnicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zawodnicy` (
  `id_zawodnika` INT NOT NULL AUTO_INCREMENT,
  `imie_zawodnika` VARCHAR(45) NOT NULL,
  `nazwisko_zawodnika` VARCHAR(45) NOT NULL,
  `pozycja_zawodnika` ENUM('Bramkarz', 'Obrońca', 'Pomocnik', 'Napastnik') NOT NULL,
  `numer_zawodnika` INT NOT NULL,
  `data_urodzenia_zawodnika` DATE NOT NULL,
  `narodowosc_zawodnika` VARCHAR(80) NOT NULL,
  `druzyna_zawodnika` INT NOT NULL,
  PRIMARY KEY (`id_zawodnika`),
  INDEX `fk_1_idx` (`druzyna_zawodnika` ASC) VISIBLE,
  CONSTRAINT `fk_1`
    FOREIGN KEY (`druzyna_zawodnika`)
    REFERENCES `mydb`.`druzyny` (`id_druzyny`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mecze`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mecze` (
  `id_meczu` INT NOT NULL AUTO_INCREMENT,
  `gospodarze_id` INT NOT NULL,
  `goscie_id` INT NOT NULL,
  `stadion_id` INT NOT NULL,
  `data_meczu` DATE NOT NULL,
  `runda_rozgrywek` INT NOT NULL,
  `gospodarze_gole` INT NOT NULL,
  `goscie_gole` INT NOT NULL,
  PRIMARY KEY (`id_meczu`),
  INDEX `fk_4_idx` (`gospodarze_id` ASC) VISIBLE,
  INDEX `fk_5_idx` (`goscie_id` ASC) VISIBLE,
  INDEX `fk_6_idx` (`stadion_id` ASC) VISIBLE,
  CONSTRAINT `fk_4`
    FOREIGN KEY (`gospodarze_id`)
    REFERENCES `mydb`.`druzyny` (`id_druzyny`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_5`
    FOREIGN KEY (`goscie_id`)
    REFERENCES `mydb`.`druzyny` (`id_druzyny`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_6`
    FOREIGN KEY (`stadion_id`)
    REFERENCES `mydb`.`stadiony` (`id_stadionu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sedziowie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sedziowie` (
  `id_sedziego` INT NOT NULL AUTO_INCREMENT,
  `imie_sedziego` VARCHAR(45) NOT NULL,
  `nazwisko_sedziego` VARCHAR(45) NOT NULL,
  `narodowosc_sedziego` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_sedziego`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sedziowie_meczow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sedziowie_meczow` (
  `mecz_id` INT NOT NULL,
  `sedzia_id` INT NOT NULL,
  `rola` VARCHAR(45) NOT NULL,
  INDEX `fk_7_idx` (`sedzia_id` ASC) VISIBLE,
  INDEX `fk_8_idx` (`mecz_id` ASC) VISIBLE,
  PRIMARY KEY (`mecz_id`, `sedzia_id`),
  CONSTRAINT `fk_7`
    FOREIGN KEY (`sedzia_id`)
    REFERENCES `mydb`.`sedziowie` (`id_sedziego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_8`
    FOREIGN KEY (`mecz_id`)
    REFERENCES `mydb`.`mecze` (`id_meczu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
