services:
  db:
    image: mariadb:latest
    container_name: football-db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: football_league

    ports:
      - "3307:3306"

    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
  
  backend:
    build: ./backend
    container_name: football-backend

    restart: always

    ports:
      - "3000:3000"

    volumes:
      - ./backend:/app
      - /app/node_modules
    
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: football-frontend

    restart: always

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - backend
      - db

    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"

volumes:
  mariadb_data: