-- MySQL Script generated by MySQL Workbench
-- Updated version with additional constraints

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `ligaPilkarska` DEFAULT CHARACTER SET utf8mb4;
USE `ligaPilkarska`;

-- -----------------------------------------------------
-- Table `trenerzy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trenerzy` (
  `id_trenera` INT NOT NULL AUTO_INCREMENT,
  `imie_trenera` VARCHAR(45) NOT NULL,
  `nazwisko_trenera` VARCHAR(45) NOT NULL,
  `narodowosc_trenera` VARCHAR(80) NOT NULL,
  `data_urodzenia_trenera` DATE NOT NULL,
  PRIMARY KEY (`id_trenera`)
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `stadiony`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stadiony` (
  `id_stadionu` INT NOT NULL AUTO_INCREMENT,
  `nazwa_stadionu` VARCHAR(45) NOT NULL,
  `lokalizacja_stadionu` VARCHAR(45) NOT NULL,
  `pojemnosc_stadionu` INT NOT NULL,
  PRIMARY KEY (`id_stadionu`),
  UNIQUE INDEX `nazwa_stadionu_UNIQUE` (`nazwa_stadionu` ASC) ,
  CONSTRAINT `chk_pojemnosc_stadionu`
    CHECK (`pojemnosc_stadionu` > 0)
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `druzyny`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `druzyny` (
  `id_druzyny` INT NOT NULL AUTO_INCREMENT,
  `nazwa_druzyny` VARCHAR(45) NOT NULL,
  `miasto_druzyny` VARCHAR(45) NOT NULL,
  `stadion` INT NOT NULL,
  `trener` INT NOT NULL,
  PRIMARY KEY (`id_druzyny`),
  UNIQUE INDEX `trener_UNIQUE` (`trener` ASC) ,
  UNIQUE INDEX `nazwa_druzyny_UNIQUE` (`nazwa_druzyny` ASC) ,
  INDEX `fk_2_idx` (`trener` ASC) ,
  INDEX `fk_3_idx` (`stadion` ASC) ,

  CONSTRAINT `fk_2`
    FOREIGN KEY (`trener`)
    REFERENCES `trenerzy` (`id_trenera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  CONSTRAINT `fk_3`
    FOREIGN KEY (`stadion`)
    REFERENCES `stadiony` (`id_stadionu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `zawodnicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zawodnicy` (
  `id_zawodnika` INT NOT NULL AUTO_INCREMENT,
  `imie_zawodnika` VARCHAR(45) NOT NULL,
  `nazwisko_zawodnika` VARCHAR(45) NOT NULL,
  `pozycja_zawodnika` ENUM('Bramkarz', 'Obrońca', 'Pomocnik', 'Napastnik') NOT NULL,
  `numer_zawodnika` INT NOT NULL,
  `data_urodzenia_zawodnika` DATE NOT NULL,
  `narodowosc_zawodnika` VARCHAR(80) NOT NULL,
  `druzyna_zawodnika` INT NOT NULL,

  PRIMARY KEY (`id_zawodnika`),

  UNIQUE INDEX `unique_numer_w_druzynie`
    (`druzyna_zawodnika`, `numer_zawodnika`) ,

  INDEX `fk_1_idx` (`druzyna_zawodnika` ASC) ,

  CONSTRAINT `fk_1`
    FOREIGN KEY (`druzyna_zawodnika`)
    REFERENCES `druzyny` (`id_druzyny`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `mecze`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mecze` (
  `id_meczu` INT NOT NULL AUTO_INCREMENT,
  `gospodarze_id` INT NOT NULL,
  `goscie_id` INT NOT NULL,
  `stadion_id` INT NOT NULL,
  `data_meczu` DATE NOT NULL,
  `runda_rozgrywek` INT NOT NULL,
  `gospodarze_gole` INT NOT NULL,
  `goscie_gole` INT NOT NULL,

  PRIMARY KEY (`id_meczu`),

  INDEX `fk_4_idx` (`gospodarze_id` ASC) ,
  INDEX `fk_5_idx` (`goscie_id` ASC) ,
  INDEX `fk_6_idx` (`stadion_id` ASC) ,

  CONSTRAINT `fk_4`
    FOREIGN KEY (`gospodarze_id`)
    REFERENCES `druzyny` (`id_druzyny`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  CONSTRAINT `fk_5`
    FOREIGN KEY (`goscie_id`)
    REFERENCES `druzyny` (`id_druzyny`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  CONSTRAINT `fk_6`
    FOREIGN KEY (`stadion_id`)
    REFERENCES `stadiony` (`id_stadionu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  CONSTRAINT `chk_rozne_druzyny`
    CHECK (`gospodarze_id` <> `goscie_id`),

  CONSTRAINT `chk_gospodarze_gole`
    CHECK (`gospodarze_gole` >= 0),

  CONSTRAINT `chk_goscie_gole`
    CHECK (`goscie_gole` >= 0)
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `sedziowie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sedziowie` (
  `id_sedziego` INT NOT NULL AUTO_INCREMENT,
  `imie_sedziego` VARCHAR(45) NOT NULL,
  `nazwisko_sedziego` VARCHAR(45) NOT NULL,
  `narodowosc_sedziego` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_sedziego`)
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `sedziowie_meczow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sedziowie_meczow` (
  `mecz_id` INT NOT NULL,
  `sedzia_id` INT NOT NULL,
  `rola` VARCHAR(45) NOT NULL,

  PRIMARY KEY (`mecz_id`, `sedzia_id`),

  INDEX `fk_7_idx` (`sedzia_id` ASC) ,
  INDEX `fk_8_idx` (`mecz_id` ASC) ,

  CONSTRAINT `fk_7`
    FOREIGN KEY (`sedzia_id`)
    REFERENCES `sedziowie` (`id_sedziego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  CONSTRAINT `fk_8`
    FOREIGN KEY (`mecz_id`)
    REFERENCES `mecze` (`id_meczu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;